<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Short-intro-to-NumPy" data-toc-modified-id="Short-intro-to-NumPy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Short intro to NumPy</a></span></li><li><span><a href="#Introduction-to-Pandas-Library" data-toc-modified-id="Introduction-to-Pandas-Library-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Introduction to Pandas Library</a></span><ul class="toc-item"><li><span><a href="#Key-Features-of-Pandas" data-toc-modified-id="Key-Features-of-Pandas-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Key Features of Pandas</a></span></li><li><span><a href="#DataFrames-and-Series-in-Pandas" data-toc-modified-id="DataFrames-and-Series-in-Pandas-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>DataFrames and Series in Pandas</a></span></li></ul></li><li><span><a href="#Series-in-Pandas" data-toc-modified-id="Series-in-Pandas-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Series in Pandas</a></span><ul class="toc-item"><li><span><a href="#Creating-Series" data-toc-modified-id="Creating-Series-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Creating Series</a></span><ul class="toc-item"><li><span><a href="#From-a-list" data-toc-modified-id="From-a-list-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>From a list</a></span></li><li><span><a href="#From-a-list-with-index" data-toc-modified-id="From-a-list-with-index-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>From a list with index</a></span></li><li><span><a href="#From-a-dictionary" data-toc-modified-id="From-a-dictionary-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>From a dictionary</a></span></li><li><span><a href="#From-a-file" data-toc-modified-id="From-a-file-3.1.4"><span class="toc-item-num">3.1.4&nbsp;&nbsp;</span>From a file</a></span></li></ul></li><li><span><a href="#Data-access-in-Series" data-toc-modified-id="Data-access-in-Series-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Data access in Series</a></span></li><li><span><a href="#Methods-in-Series" data-toc-modified-id="Methods-in-Series-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Methods in Series</a></span><ul class="toc-item"><li><span><a href="#concat()" data-toc-modified-id="concat()-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span><code>concat()</code></a></span></li><li><span><a href="#sort_values()-and-sort_index()" data-toc-modified-id="sort_values()-and-sort_index()-3.3.2"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span><code>sort_values() and sort_index()</code></a></span></li><li><span><a href="#value_counts()" data-toc-modified-id="value_counts()-3.3.3"><span class="toc-item-num">3.3.3&nbsp;&nbsp;</span><code>value_counts()</code></a></span></li></ul></li><li><span><a href="#💡-Check-for-understanding" data-toc-modified-id="💡-Check-for-understanding-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>💡 Check for understanding</a></span></li></ul></li><li><span><a href="#Dataframes-in-Pandas" data-toc-modified-id="Dataframes-in-Pandas-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Dataframes in Pandas</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#head()-and-tail()" data-toc-modified-id="head()-and-tail()-4.0.1"><span class="toc-item-num">4.0.1&nbsp;&nbsp;</span><code>head()</code> and <code>tail()</code></a></span></li><li><span><a href="#index,-columns-and-values" data-toc-modified-id="index,-columns-and-values-4.0.2"><span class="toc-item-num">4.0.2&nbsp;&nbsp;</span><code>index, columns and values</code></a></span></li></ul></li><li><span><a href="#Data-access-in-Dataframe" data-toc-modified-id="Data-access-in-Dataframe-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Data access in Dataframe</a></span><ul class="toc-item"><li><span><a href="#Columns" data-toc-modified-id="Columns-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>Columns</a></span></li><li><span><a href="#Rows" data-toc-modified-id="Rows-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span>Rows</a></span></li><li><span><a href="#Specific-values" data-toc-modified-id="Specific-values-4.1.3"><span class="toc-item-num">4.1.3&nbsp;&nbsp;</span>Specific values</a></span></li></ul></li><li><span><a href="#More-DataFrame-Methods" data-toc-modified-id="More-DataFrame-Methods-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>More DataFrame Methods</a></span><ul class="toc-item"><li><span><a href="#shape" data-toc-modified-id="shape-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span><code>shape</code></a></span></li><li><span><a href="#describe()" data-toc-modified-id="describe()-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span><code>describe()</code></a></span></li><li><span><a href="#info()" data-toc-modified-id="info()-4.2.3"><span class="toc-item-num">4.2.3&nbsp;&nbsp;</span><code>info()</code></a></span></li><li><span><a href="#nunique()-and-unique()" data-toc-modified-id="nunique()-and-unique()-4.2.4"><span class="toc-item-num">4.2.4&nbsp;&nbsp;</span><code>nunique() and unique()</code></a></span></li><li><span><a href="#dtypes" data-toc-modified-id="dtypes-4.2.5"><span class="toc-item-num">4.2.5&nbsp;&nbsp;</span><code>dtypes</code></a></span></li><li><span><a href="#select_dtypes()" data-toc-modified-id="select_dtypes()-4.2.6"><span class="toc-item-num">4.2.6&nbsp;&nbsp;</span><code>select_dtypes()</code></a></span></li><li><span><a href="#Aggregation-such-as-max()" data-toc-modified-id="Aggregation-such-as-max()-4.2.7"><span class="toc-item-num">4.2.7&nbsp;&nbsp;</span>Aggregation such as <code>max()</code></a></span></li></ul></li><li><span><a href="#💡-Check-for-understanding" data-toc-modified-id="💡-Check-for-understanding-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>💡 Check for understanding</a></span></li></ul></li><li><span><a href="#Summary" data-toc-modified-id="Summary-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Summary</a></span></li><li><span><a href="#Extra:-Creating-Dataframes-from-a-Dictionary" data-toc-modified-id="Extra:-Creating-Dataframes-from-a-Dictionary-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Extra: Creating Dataframes from a Dictionary</a></span></li><li><span><a href="#Extra:-pickle" data-toc-modified-id="Extra:-pickle-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Extra: pickle</a></span><ul class="toc-item"><li><span><a href="#Saving-DataFrames-with-Pickle" data-toc-modified-id="Saving-DataFrames-with-Pickle-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Saving DataFrames with Pickle</a></span></li><li><span><a href="#Loading-DataFrames-from-Pickle" data-toc-modified-id="Loading-DataFrames-from-Pickle-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Loading DataFrames from Pickle</a></span></li></ul></li></ul></div>

# Short intro to NumPy

Let's start with the first library to be used in this bootcamp:
[NumPy](https://numpy.org/)

NumPy is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices thorugh classes, along with an extensive collection of mathematical functions and methods to operate on these arrays efficiently.



To use a library in our code, first we need to make sure that the library is installed in our computer. In the case of NumPy, we don't need to worry about this because it's installed during the installation of Anaconda.

If the library that we pretend to use is not installed in our computer we will have to use a "package manager" as Anaconda to do it. However, we will cover this later during the bootcamp.

The next step is to make it available in our code. This process is called "importing" the library. There are several ways to "import" code from a library in our programs:

1. Import the whole library or some functions from the library. We can do this by simply adding the line shown below in our code.

```
import library_name
```

replacing the `library_name` by the name of the library that we pretend to use.

If a function of the library, has the same name as a Python built-in function, it will overwrite it. To avoid this potential problem, we can use an alias during the "import" as shown below:

```
import library_name as alias
````

where the name of the alias can be anything. However, the coding comunity uses specific aliases for each of the most commonly used libraries. Thus, whenever someone uses an alias in a code everybody knows which library refers to.

Finally, there are some huge libraries, and not allways we want to use all the code from a given library. In such cases, we can only "import" a subset of clases, methods, functions...etc from the given library. To do this, we can use the syntax shown below:

```
from library import function, class,...
````


Aside from new data types (np.int, np.float, np.bool,...) introduced by Numpy, Numpy comes with a new important class that allows us to handle arrays and to speed up numerical calculations in a more intuitive way.

Let's import Numpy in our code. In case of Numpy, all the developers use "np" as an alias for Numpy.

In [ ]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

print(arr)

# Array elements can be accessed by index like a Python list.
print(arr[0])

# Performing operations on the array
result = arr * 2
print("Result with a numpy array: ",result)  # Output: [2 4 6 8 10]

# Notice the difference between arr * 2 if arr is a Numpy array or a Python list
print("Result with a Python list: ",[1, 2, 3, 4, 5] * 2)


[1 2 3 4 5]
1
Result with a numpy array:  [ 2  4  6  8 10]
Result with a Python list:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


However, Numpy arrays introduce a restition on the allowed data types of each element in the array: all the elements must be of the same primitive data type. This in in clear contrast with Python lists where  the elements can be of heterogeneous data types (one element can be boolean, another can be a list, the other a dictionary, and so on). If the elements of a Numpy array are from different data types, Numpy will try to cast all the elements to a common type. If it's not possible to do the casting it will raise an error.

In [ ]:
np.__version__

'1.26.4'

In [ ]:
a = np.array(["Hello", 1, False])
a

array(['Hello', '1.2', 'False'], dtype='<U32')

As we can see, all the elements were casted as "strings"

The previous example involved a 1D-Numpy array. However Numpy arrays can have multiple dimensions: 2, 3, 4...etc, and each dimension will have an index associated.

Let's see an example of a 2d-array. 2d-arrays can be unsderstood as tables of data. However, these tables lack of column/row names.

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
# This array has three rows and two columns.
# To retrieve an element, we need to provide the index for the row, and the index for the column separated by "," within brackets.

print("The element in the first row and second column is: ",a[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

The element in the first row and second column is:  2


# Slicing Numpy arrays

Sometimes we want to access a subset of rows/columns from the NumPy array. To do this, we can use the following syntax:

```
a[n:m, p:q]
```

which means: retrieve all the elements from row "n" to row "m-1" (the last one is not included) and columns "p" to "q-1".

Let's see an example!

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[-2, -5, -6, 3]])
print(a)
print()
print(a[1:3,1:3]) # row indices: 1,3,-> 1:4 columns indices: 1,3 -> 1:3

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [-2 -5 -6  3]]

[[ 6  7]
 [10 11]]


When we use slicing, we can ommit one or both numbers from the "n:m" syntax. Let's see all the possible cases:

1. If we ommit "n", we will retrieve all the rows from the first one to "m-1".
2. If we ommit "m", we will retrieve all the rows from the "m" one to the last one
3. If we ommit both, we will obtain all the rows.

The same applies for column indexes.

In [ ]:
print(a)
print()
print(a[1:, 2: ])
print()
print(a[:2, :2])
print()
print(a[:2, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [-2 -5 -6  3]]

[[ 7  8]
 [11 12]
 [-6  3]]

[[1 2]
 [5 6]]

[[1 2 3 4]
 [5 6 7 8]]


# Filters

We can also add filters placing our condition within brackets

In [ ]:
print(a[a> 5])

[ 6  7  8  9 10 11 12]


# Some important attributes of the Numpy array class

Numpy arrays are instances of the class "array". This class has a few important attributes that deserve special attention for us: `.shape`, `.ndim`, and `.size`.

The `.shape` attribute returns a tuple with two elements: the number of rows, and the number of columns.

In [ ]:
print(a.shape)
print()
print(f"The Numpy array has {a.shape[0]} rows, and {a.shape[1]} columns")
print()
print(f"The number of dimensions is: {a.ndim}")
print()
print(f"The number of elements in the Numpy array is: {a.size}")

(4, 4)

The Numpy array has 4 rows, and 4 columns

The number of dimensions is: 2

The number of elements in the Numpy array is: 16


# Checking our Numpy version

In Python, all the libraries are constantly changing with new updates and some functions might become deprecated over time. Therefore, it's important to know how to determine the current version of a library. This is very easy to do, we can symply type:

```
np.__version__
```

then, when we go to the official page, we need to make sure that we are checking the documentation that corresponds to our case.

In [ ]:
np.__version__

'1.26.4'

# Introduction to Pandas Library

`pandas` is a powerful library designed for working with tabulated and tagged data, making it ideal for handling spreadsheets, SQL tables, and more. It introduces two new classes: `Series` and `DataFrames`.

## Key Features of Pandas

- Robust data import/export: `pandas` provides efficient tools to read and write data from various file formats like CSV, XLS, SQL, and HDF5.
- Data manipulation: With `pandas`, you can easily filter, add, or delete data, enabling seamless data processing.
- High-performance and versatility: It combines the performance of `numpy` arrays with the ability to handle tabulated data efficiently.

To import the necessary modules from the `pandas` library, we use the following syntax:

In [ ]:
import pandas as pd  # 'pd' is an alias for pandas

![](https://github.com/data-bootcamp-v4/lessons/blob/main/img/pandas.svg?raw=true)

## DataFrames and Series in Pandas

In `pandas`, a `Series` is a one-dimensional array of data with associated labels called the *index*. If no index is specified, it will automatically generates an ordered sequence of integers as indexes.

```python
# Creating a Series
s = pd.Series(data, index=index)
```

On the other hand, a `DataFrame` is a two-dimensional data structure that stores data in tabular form, with labeled rows and columns. There are a couple of key differences between Numpy arrays and Pandas DataFrames. First, DataFrames have column/row names while Numpye arrays don't. Second, the data types of each column can be different.

Each row represents an observation, and each column represents a variable. `DataFrame` can handle heterogeneous data with different types (numeric, string, boolean, etc.). It also includes variable names, types, and methods to access and modify the data.

```python
# Creating a DataFrame
df = pd.DataFrame(data, ...)
```


---
# Series in Pandas

## Creating Series


### From a list

Create a Series with default indexes from a list

In [ ]:
np.array([1980, 2020, 2001, 1999])

array([1980, 2020, 2001, 1999])

In [ ]:
l = [1980, 2020, 2001, 1999]
series = pd.Series(l)
# Here, we haven't specified the indexes. Therefore, Pandas will automatically set the indexes as consecutive
# integer numbers starting from 0
series #we can see dtype int which means the series has integers

0    1980
1    2020
2    2001
3    1999
dtype: int64

In [ ]:
type(series) #but careful, its still a pandas series

pandas.core.series.Series

In [ ]:
series.dtype #this gives me the type of the elements inside the series
# this is an attribute (remember our lesson about classes)

dtype('int64')

The `Series` have two important attributes:` values` and `index`. The first is a `numpy array` that stores the data, and the second is an object that contains the indexes.

In [ ]:
series.values

array([1980, 2020, 2001, 1999])

In [ ]:
series.index

RangeIndex(start=0, stop=4, step=1)

In this sense, Pandas Series can be understood as Python dictionaries where the keys are the indexes and the values are the values.

In Pandas, `Series.items()` is a method used to iterate over the elements of a Pandas Series. It returns an iterator that yields the index-label and corresponding value pairs of the Series.

In [ ]:
for key in series.keys():
    print(key)

0
1
2
3


In [ ]:
#items has tuples (index,value) so i need to iterate with two variables
# if i want the values separated, if not, i get the tuple in each
# iteration
for i in series.index:
    print(i)

for key, value in series.items():
    print(key, value)

0
1
2
3
0 1980
1 2020
2 2001
3 1999


In [ ]:
for i, v in series.items() :
    print("index ", i)
    print("value ", v)

index  0
value  1980
index  1
value  2020
index  2
value  2001
index  3
value  1999


### From a list with index

When creating a `Series`, you can explicitly define an `array` index and pass it as an argument.


Creating series with defined indexes

In [ ]:
# create a new series with same values as before, and as indexes, names
# values [1980, 2020, 2001, 1999]
# index "deb","d","martha", "martin"
new_series = pd.Series([1980, 2020, 2001, 1999],
                       index = ["deb","d","martha", "martin"])
new_series

deb       1980
d         2020
martha    2001
martin    1999
dtype: int64

### From a dictionary

In [ ]:
# using dict comprehension, create a dictionary
# that has as key "square of {nr}" and as value the nr squared
# for values from 0 to 10
d = {"square of "+str(n): n*n for n in range(11)}
d

{'square of 0': 0,
 'square of 1': 1,
 'square of 2': 4,
 'square of 3': 9,
 'square of 4': 16,
 'square of 5': 25,
 'square of 6': 36,
 'square of 7': 49,
 'square of 8': 64,
 'square of 9': 81,
 'square of 10': 100}

In [ ]:
pd.Series(d) # this creates a series from the dictionary 'd'

square of 0       0
square of 1       1
square of 2       4
square of 3       9
square of 4      16
square of 5      25
square of 6      36
square of 7      49
square of 8      64
square of 9      81
square of 10    100
dtype: int64

In [ ]:
pd.Series({str(n): n*n for n in range(11)})

0       0
1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
dtype: int64


# Dataframes in Pandas

Unlike `Series`, `DataFrame` is designed to store heterogeneous multivariable data. It can be created from dictionaries (look to Extra section for examples).

We will use `read_csv` to read data from a CSV file and create a DataFrame.

We won't be using now the parameter `usecols` nor calling the method `squeeze("columns")`.

In [1]:
# Load Titanic dataset from an online source
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/titanic_train.csv'
titanic_df = pd.read_csv(url)
titanic_df

NameError: name 'pd' is not defined

As we can see, with Pandas DataFrames we can read tabular data which was not possible with Numpy arrays. In addition, now every column/row will have "labels" and "indexes"! Therefore, we will be able to access to a subset of column/rows by using either "labels" or "indexes" but not both.

# Some important methods of Pandas DataFrames

### `head()` and `tail()`

The `head()` method returns the first few rows of a DataFrame or Series, while the `tail()` method returns the last few rows.

In [ ]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
titanic_df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

### `index, columns and values`

The `index` attribute in Pandas returns the index labels of a DataFrame or Series, and the `columns` attribute returns the column labels of a DataFrame.

In [ ]:
titanic_df.index

RangeIndex(start=0, stop=891, step=1)

`RangeIndex(start=0, stop=1460, step=1)` is a special type of index in Pandas called a `RangeIndex`. It represents a range of integer values starting from 0, up to (but not including) 1460, with a step size of 1.

In [ ]:
list(titanic_df.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


We can have access to the column's names using the `.columns` attribute

In [ ]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
list(titanic_df.columns)

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In Pandas, `df.values` is an attribute that returns the underlying NumPy array of a DataFrame df. It represents the actual data stored in the DataFrame as a two-dimensional NumPy array.

In [ ]:
titanic_df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)


Additionally, `Pandas` can create Dataframes from other sources, such as JSON, URL ...


---
## Data access in Dataframe


### Columns

You can extract columns from a `DataFrame` using dictionary-like notation or as attributes, obtaining a `Series` object in both cases, provided the column label is a valid Python identifier.

In [ ]:
titanic_df["Sex"] #dict way of accessing a column

0        male
1      female
2      female
3      female
4        male
        ...  
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [ ]:
titanic_df.Sex #attribute access of the column

#this only works if the column name doesn't have unusual characters, this means
#no spaces!!! Therefore, it's important to make sure that the DataFrame doesn't contain columns with white spaces!!!

0        male
1      female
2      female
3      female
4        male
        ...  
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [ ]:
titanic_df[["Sex"]] #by using double [] we get a Dataframe instead
# of a series

Sex
0      male
1    female
2    female
3    female
4      male
..      ...
886    male
887  female
888  female
889    male
890    male

[891 rows x 1 columns]

We can access a subset of columns by providing a list of the desired column's names within square brackets.

In [ ]:
titanic_df[["Sex","Fare"]]

Sex     Fare
0      male   7.2500
1    female  71.2833
2    female   7.9250
3    female  53.1000
4      male   8.0500
..      ...      ...
886    male  13.0000
887  female  30.0000
888  female  23.4500
889    male  30.0000
890    male   7.7500

[891 rows x 2 columns]

### Rows

To access rows in a Pandas DataFrame, you can use the `iloc` attribute with integer-based indexing or the `loc` attribute with label-based indexing. For example, `df.iloc[0]` will access the first row, and `df.loc['row_label']` will access the row with the specified label.


<div class="alert alert-info">Note: Consult http://pandas.pydata.org/pandas-docs/version/0.18.1/indexing.html#different-choices-for-indexing to understand the differences between methods.</div>

Just for the sake of this example, we will create Panda's DataFrame from a dictionary. However, to do so the values of each key must be lists. If we do so, the dictionary keys will become the column names and the values contained in the list will become the entries

In [ ]:
d_index = {
    "name": ["Paula", "Mark"],
    "score": [98.5, 95]
}

df_index = pd.DataFrame(d_index, index=["123A", "789B"])
df_index

name  score
123A  Paula   98.5
789B   Mark   95.0


**loc** is used for label-based indexing to access rows.

In [ ]:
df_index.loc["789B"]

name     Mark
score    95.0
Name: 789B, dtype: object


**iloc** is used for integer-based indexing in Pandas to access rows

In [ ]:
df_index.iloc[1]

name     Mark
score    95.0
Name: 789B, dtype: object

### Specific values

Here's a summary of the different ways to access individual values in a Pandas DataFrame:

1. `df.loc[row_label][column_label]`: Chooses the row with the label and then the value in that row with the column label.

2. `df.iloc[row_position][column_label]`: Selects the row with the position and then the value in that row with the column label.

3. `df.loc[row_label, column_label]`: Directly accesses the value using both row and column labels.

4. `df.iloc[row_position, column_position]`: Directly accesses the value using both row and column positions.

Note: you might see `df[row_label][column_label]`, even though is less recommended that using `loc()`.

In [ ]:
# first I access the row with the index, then I access the value
# with the index of the resulting series (name of the column)
df_index.iloc[0]["score"]

98.5

In [ ]:
# first I access the row with the label, then I access the value
# with the index of the resulting series (name of the column)
df_index.loc["789B"]["score"]

95.0

In [ ]:
df_index.loc["789B","score"]

95.0


---
## More DataFrame Methods


Let's see some useful methods of the Dataframe class.

### `shape`

`shape` is a Pandas attribute that returns a tuple representing the dimensions of a DataFrame or Series, indicating the number of rows and columns, while `shape()` is not a valid function in Pandas, and attempting to call it will result in an AttributeError.

In [ ]:
titanic_df.shape # gives a tuple (nr rows, nr columns)

(891, 12)

In [ ]:
titanic_df.shape[1] #tuples are accesed like this. nr of columns

12

In [ ]:
titanic_df.shape[0] # nr of rows

891

### `describe()`

`describe()` is a Pandas method that generates descriptive statistics of a DataFrame, providing information on count, mean, standard deviation, minimum, maximum, and quartiles for each numerical column.

In [ ]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
titanic_df.describe(include="object")

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [ ]:
titanic_df.describe(include="all")

PassengerId    Survived      Pclass                     Name   Sex  \
count    891.000000  891.000000  891.000000                      891   891   
unique          NaN         NaN         NaN                      891     2   
top             NaN         NaN         NaN  Braund, Mr. Owen Harris  male   
freq            NaN         NaN         NaN                        1   577   
mean     446.000000    0.383838    2.308642                      NaN   NaN   
std      257.353842    0.486592    0.836071                      NaN   NaN   
min        1.000000    0.000000    1.000000                      NaN   NaN   
25%      223.500000    0.000000    2.000000                      NaN   NaN   
50%      446.000000    0.000000    3.000000                      NaN   NaN   
75%      668.500000    1.000000    3.000000                      NaN   NaN   
max      891.000000    1.000000    3.000000                      NaN   NaN   

               Age       SibSp       Parch  Ticket        Fare    Cabin  \
count   714.000000  891.000000  891.000000     891  891.000000      204   
unique         NaN         NaN         NaN     681         NaN      147   
top            NaN         NaN         NaN  347082         NaN  B96 B98   
freq           NaN         NaN         NaN       7         NaN        4   
mean     29.699118    0.523008    0.381594     NaN   32.204208      NaN   
std      14.526497    1.102743    0.806057     NaN   49.693429      NaN   
min       0.420000    0.000000    0.000000     NaN    0.000000      NaN   
25%      20.125000    0.000000    0.000000     NaN    7.910400      NaN   
50%      28.000000    0.000000    0.000000     NaN   14.454200      NaN   
75%      38.000000    1.000000    0.000000     NaN   31.000000      NaN   
max      80.000000    8.000000    6.000000     NaN  512.329200      NaN   

       Embarked  
count       889  
unique        3  
top           S  
freq        644  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

### `info()`

`info()` is a Pandas method that provides a concise summary of a DataFrame, including information about the data types, non-null values, and memory usage.

In [ ]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


### `nunique() and unique()`

`nunique()` is a Pandas function that returns the number of unique elements in a Series or DataFrame, while `unique()` returns an array of unique elements in a Series or DataFrame.

In [ ]:
titanic_df.nunique() #number of unique values per column

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [ ]:
titanic_df.Pclass.nunique()

3

In [ ]:
#see unique values of one column
titanic_df.Pclass.unique() # M, F, male, Male, maaale, ....

array([3, 1, 2])

### `dtypes`

`dtypes` is a Pandas attribute that returns the data types of each column in a DataFrame, while `dtype` is a method that returns the data type of a single element in a Series or DataFrame.

In [ ]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### `select_dtypes()`

`select_dtypes()` is a pandas function used to filter columns in a DataFrame based on their data types. It allows you to select numeric, object (string), boolean, datetime, or categorical columns.

Syntax:
```python
DataFrame.select_dtypes(include=None, exclude=None)
```

- `include`: A list of data types or strings representing data types to include in the selection. If specified, only columns with these data types will be included.
- `exclude`: A list of data types or strings representing data types to exclude from the selection. If specified, columns with these data types will be excluded.

Example:
```python
# Assuming df is a DataFrame
numeric_columns = df.select_dtypes(include='number')
object_columns = df.select_dtypes(include='object')
```



In [ ]:
titanic_df.select_dtypes(include=['int','float'])

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [ ]:
titanic_df.select_dtypes(include='number')#.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

### Aggregation such as `max()`

In [ ]:
titanic_df.select_dtypes(include='number').max() #get the max for each numerical column in the df

PassengerId    891.0000
Survived         1.0000
Pclass           3.0000
Age             80.0000
SibSp            8.0000
Parch            6.0000
Fare           512.3292
dtype: float64

In [ ]:
titanic_df.Fare.max() #get the max for one numerical column

512.3292

In [ ]:
titanic_df.iloc[:,[list(titanic_df.columns).index("Age"),list(titanic_df.columns).index("Fare")]].max()

Age      80.0000
Fare    512.3292
dtype: float64

In [ ]:
titanic_df[["Age","Fare"]].max()

Age      80.0000
Fare    512.3292
dtype: float64

 Just like `max()`, there are many methods that can be applied to either the entire dataframe or its individual columns.

## 💡 Check for understanding

.value_counts()

- a. Use the original titanic_df
- b. Select the `Sex` and `Fare` columns.
- c. Indicate how many different types of `Sex` there are.
- d. Indicate how many `Sex` of each type there are.
- e. Show a statistical summary of all the variables.
- f. Write some conclusions

In [11]:
import pandas as pd
titanic_df=pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/titanic_train.csv')


In [21]:
titanic_df[["Sex", "Fare"]]


Sex     Fare
0      male   7.2500
1    female  71.2833
2    female   7.9250
3    female  53.1000
4      male   8.0500
..      ...      ...
886    male  13.0000
887  female  30.0000
888  female  23.4500
889    male  30.0000
890    male   7.7500

[891 rows x 2 columns]

In [9]:
titanic_df["Sex"].nunique()


2

In [13]:
titanic_df["Sex"].value_counts()


Sex
male      577
female    314
Name: count, dtype: int64

# Summary

- Pandas is a library designed for working with tabulated and tagged data, making it ideal for handling spreadsheets, SQL tables, and more, built on top of NumPy.
- DataFrames and Series are the two main data structures in Pandas.
- Series is a one-dimensional array of data with associated labels called the index, while DataFrame is a two-dimensional tabular data structure with labeled rows and columns.
- Data access in Series and DataFrame can be achieved using integer-based indexing (iloc), label-based indexing (loc), or dictionary-like notation for column access.
- Series and DataFrame have various methods, such as sort_values(), sort_index(), value_counts(), describe(), info(), nunique(), unique(), dtypes, and select_dtypes().


In [ ]:
titanic_df.sort_values(by=["Pclass","Age"], ascending=[False,True]) #.head()#.sort_values(by="Age")

PassengerId  Survived  Pclass  \
803          804         1       3   
469          470         1       3   
644          645         1       3   
164          165         0       3   
172          173         1       3   
..           ...       ...     ...   
766          767         0       1   
793          794         0       1   
815          816         0       1   
839          840         1       1   
849          850         1       1   

                                             Name     Sex   Age  SibSp  Parch  \
803               Thomas, Master. Assad Alexander    male  0.42      0      1   
469                 Baclini, Miss. Helene Barbara  female  0.75      2      1   
644                        Baclini, Miss. Eugenie  female  0.75      2      1   
164                  Panula, Master. Eino Viljami    male  1.00      4      1   
172                  Johnson, Miss. Eleanor Ileen  female  1.00      1      1   
..                                            ...     ...   ...    ...    ...   
766                     Brewe, Dr. Arthur Jackson    male   NaN      0      0   
793                      Hoyt, Mr. William Fisher    male   NaN      0      0   
815                              Fry, Mr. Richard    male   NaN      0      0   
839                          Marechal, Mr. Pierre    male   NaN      0      0   
849  Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  female   NaN      1      0   

       Ticket     Fare Cabin Embarked  
803      2625   8.5167   NaN        C  
469      2666  19.2583   NaN        C  
644      2666  19.2583   NaN        C  
164   3101295  39.6875   NaN        S  
172    347742  11.1333   NaN        S  
..        ...      ...   ...      ...  
766    112379  39.6000   NaN        C  
793  PC 17600  30.6958   NaN        C  
815    112058   0.0000  B102        S  
839     11774  29.7000   C47        C  
849     17453  89.1042   C92        C  

[891 rows x 12 columns]